# Пример env файла

env : "local" # dev, prod

postgres:
  host: "postgres://postgres:postgres@host:port/dbname?sslmode=disable"
  timeout: 5s
  max_idle_connection: 5

http_server:
  port: 8080
  timeout: 5s