basePath: /api
definitions:
  handlers.Board:
    properties:
      id:
        type: string
      name:
        type: string
      short_name:
        type: string
      updated_at:
        type: string
    type: object
  handlers.CheckListItemDto:
    properties:
      completed:
        type: boolean
      title:
        type: string
    type: object
  handlers.ChecklistDto:
    properties:
      items:
        items:
          $ref: '#/definitions/handlers.CheckListItemDto'
        type: array
      title:
        type: string
    type: object
  handlers.CreateBoardReqest:
    properties:
      name:
        type: string
      short_name:
        type: string
    type: object
  handlers.CreateBoardResponce:
    properties:
      column:
        $ref: '#/definitions/handlers.CreateColumnResponse'
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      name:
        type: string
      short_name:
        type: string
      updated_at:
        type: string
    type: object
  handlers.CreateColumnRequest:
    properties:
      name:
        type: string
    type: object
  handlers.CreateColumnResponse:
    properties:
      board_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      name:
        type: string
      order_num:
        type: integer
      updated_at:
        type: string
    type: object
  handlers.CreateTaskRequest:
    properties:
      board_id:
        type: string
      checklists:
        items:
          $ref: '#/definitions/handlers.ChecklistDto'
        type: array
      column_id:
        type: string
      description:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  handlers.CreateTaskResponse:
    properties:
      board_id:
        type: string
      checklists:
        items:
          $ref: '#/definitions/handlers.ChecklistDto'
        type: array
      column_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      number:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
  handlers.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/handlers.Error'
    type: object
  handlers.GetBoardsResponse:
    properties:
      boards:
        items:
          $ref: '#/definitions/handlers.Board'
        type: array
    type: object
  handlers.GetTaskResponse:
    properties:
      board_id:
        type: string
      checklists:
        items:
          $ref: '#/definitions/handlers.ChecklistDto'
        type: array
      column_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      number:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
  handlers.MoveTaskRequest:
    properties:
      column_id:
        type: string
    required:
    - column_id
    type: object
  handlers.MoveTaskResponse:
    properties:
      board_id:
        type: string
      checklists:
        items:
          $ref: '#/definitions/handlers.ChecklistDto'
        type: array
      column_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      number:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
  handlers.PutTaskRequest:
    properties:
      board_id:
        type: string
      checklists:
        items:
          $ref: '#/definitions/handlers.ChecklistDto'
        type: array
      column_id:
        type: string
      description:
        type: string
      number:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  handlers.PutTaskResponse:
    properties:
      board_id:
        type: string
      checklists:
        items:
          $ref: '#/definitions/handlers.ChecklistDto'
        type: array
      column_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      number:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
  handlers.SearchTaskResponse:
    properties:
      board_id:
        type: string
      board_name:
        type: string
      board_short_name:
        type: string
      column_id:
        type: string
      column_name:
        type: string
      id:
        type: string
      number:
        type: integer
      title:
        type: string
    type: object
  handlers.SearchTasksRequest:
    properties:
      filters:
        properties:
          tags:
            items:
              type: string
            type: array
        type: object
      limit:
        type: integer
      offset:
        type: integer
      query:
        type: string
    type: object
externalDocs:
  description: OpenAPI
host: localhost:8080
info:
  contact: {}
  description: API для проекта Team Board
  title: Team Board API
  version: "1.0"
paths:
  /v1/boards:
    get:
      consumes:
      - application/json
      parameters:
      - description: User-id in uuid-format
        in: header
        name: User-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GetBoardsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get boards by User-id
      tags:
      - Boards
    post:
      consumes:
      - application/json
      parameters:
      - description: request на создание доски
        in: body
        name: createBoardRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateBoardReqest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.CreateBoardResponce'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Создание новой доски
      tags:
      - Boards
  /v1/boards/{board_id}/columns:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID доски
        in: path
        name: board_id
        required: true
        type: string
      - description: request на создание колонки
        in: body
        name: createColumnRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateColumnRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.CreateColumnResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Создание новой колонки
      tags:
      - Columns
  /v1/boards/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет доску по её ID
      parameters:
      - description: ID доски
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Доска успешно удалена
        "400":
          description: Некорректный запрос или неверный ID
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Доска не найдена
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Удаление доски
      tags:
      - Boards
    get:
      consumes:
      - application/json
      parameters:
      - description: User-id in uuid-format
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GetBoardsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получение доски по id
      tags:
      - Boards
  /v1/columns/{column_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID колонки
        in: path
        name: column_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Удаление колонки по id
      tags:
      - Columns
  /v1/tasks:
    post:
      consumes:
      - application/json
      parameters:
      - description: request на создание таски
        in: body
        name: createTaskRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.CreateTaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Создание новой задачи
      tags:
      - Tasks
  /v1/tasks/{task_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID задачи
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Удаление задачи по id
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      parameters:
      - description: ID задачи
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GetTaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получение задачи по ID
      tags:
      - Tasks
    put:
      consumes:
      - application/json
      parameters:
      - description: ID задачи
        in: path
        name: task_id
        required: true
        type: string
      - description: put task request
        in: body
        name: putTaskRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.PutTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PutTaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Изменение задачи
      tags:
      - Tasks
  /v1/tasks/{task_id}/move:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID задачи
        in: path
        name: task_id
        required: true
        type: string
      - description: request на перемещение задачи
        in: body
        name: moveTaskRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.MoveTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Полная информация об обновленной задаче
          schema:
            $ref: '#/definitions/handlers.MoveTaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Перемещение задачи в другую колонку
      tags:
      - Tasks
  /v1/tasks/search:
    post:
      consumes:
      - application/json
      parameters:
      - description: request для поиска тасок
        in: body
        name: searchTasksRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.SearchTasksRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.SearchTaskResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Поиск задач по тегам и названию
      tags:
      - Tasks
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
